#include <pybind11/pybind11.h>

namespace py = pybind11;

void bind_alpha_example(py::module& m);
void bind_cube2mat_gini_absret(py::module& m);
void bind_cube2mat_n_entropy_concentration(py::module& m);
void bind_cube2mat_n_gini(py::module& m);
void bind_cube2mat_ret_skew(py::module& m);
void bind_cube2mat_rv_entropy_concentration(py::module& m);
void bind_cube2mat_rv_gini_concentration(py::module& m);
void bind_cube2mat_trade_size_gini(py::module& m);
void bind_cube2mat_trend_resid_kurt(py::module& m);
void bind_cube2mat_trend_resid_skew(py::module& m);
void bind_cube2mat_volume_entropy_concentration(py::module& m);
void bind_cube2mat_volume_gini(py::module& m);
void bind_cube2mat_volume_median_to_mean_ratio(py::module& m);
void bind_cube2mat_volume_skew(py::module& m);
void bind_cube2mat_katz_fd_close(py::module& m);
void bind_cube2mat_oc_efficiency_over_range(py::module& m);
void bind_cube2mat_path_efficiency(py::module& m);
void bind_cube2mat_path_length_over_range(py::module& m);
void bind_cube2mat_total_variation_close(py::module& m);
void bind_cube2mat_breakout_nextret_high(py::module& m);
void bind_cube2mat_breakout_nextret_low(py::module& m);
void bind_cube2mat_candle_body_to_range_mean(py::module& m);
void bind_cube2mat_close_to_edge_distance_frac(py::module& m);
void bind_cube2mat_doji_density(py::module& m);
void bind_cube2mat_end_position_in_range(py::module& m);
void bind_cube2mat_intraday_max_drawdown_close(py::module& m);
void bind_cube2mat_iqr_logret(py::module& m);
void bind_cube2mat_lower_shadow_ratio_mean(py::module& m);
void bind_cube2mat_max_drawdown_depth_per_bar(py::module& m);
void bind_cube2mat_mean_body_to_range(py::module& m);
void bind_cube2mat_median_position_in_range(py::module& m);
void bind_cube2mat_n_peak_time_frac(py::module& m);
void bind_cube2mat_near_high_time_share_10bp(py::module& m);
void bind_cube2mat_near_low_time_share_10bp(py::module& m);
void bind_cube2mat_new_high_count(py::module& m);
void bind_cube2mat_new_low_count(py::module& m);
void bind_cube2mat_parkinson_vol(py::module& m);
void bind_cube2mat_range_on_logvolume_beta(py::module& m);
void bind_cube2mat_range_per_trade(py::module& m);
void bind_cube2mat_range_to_rv_sqrt_ratio(py::module& m);
void bind_cube2mat_range_up_down_ratio(py::module& m);
void bind_cube2mat_spectral_lowfreq_share_close(py::module& m);
void bind_cube2mat_time_share_mid_range_20pct(py::module& m);
void bind_cube2mat_u_shape_corr_volume(py::module& m);
void bind_cube2mat_upper_shadow_ratio_mean(py::module& m);
void bind_cube2mat_vwap_position_in_range(py::module& m);
void bind_cube2mat_wavelet_energy_highfreq_share(py::module& m);
void bind_cube2mat_wavelet_energy_lowfreq_share(py::module& m);
void bind_cube2mat_cond_reversal_after_run2(py::module& m);
void bind_cube2mat_early_vs_late_run_count_ratio(py::module& m);
void bind_cube2mat_max_down_run_len(py::module& m);
void bind_cube2mat_max_up_run_len(py::module& m);
void bind_cube2mat_mean_run_length_sign(py::module& m);
void bind_cube2mat_quietest_stretch_maxlen_q25_absret_frac(py::module& m);
void bind_cube2mat_run_balance_index(py::module& m);
void bind_cube2mat_run_len_var_ratio_up_to_down(py::module& m);
void bind_cube2mat_run_length_entropy_signret(py::module& m);
void bind_cube2mat_sign_change_rate(py::module& m);
void bind_cube2mat_swing_amplitude_median(py::module& m);
void bind_cube2mat_transition_p_same_sign(py::module& m);
void bind_cube2mat_approx_entropy_absret_m2_r02(py::module& m);
void bind_cube2mat_entropy_sign_ret(py::module& m);
void bind_cube2mat_higuchi_fd_logret_kmax7(py::module& m);
void bind_cube2mat_permutation_entropy_logret_m3(py::module& m);
void bind_cube2mat_permutation_entropy_ret(py::module& m);
void bind_cube2mat_sample_entropy_absret_m2_r02(py::module& m);
void bind_cube2mat_transition_entropy_signret(py::module& m);
void bind_cube2mat_volume_entropy(py::module& m);
void bind_cube2mat_corr_absret_n(py::module& m);
void bind_cube2mat_corr_ret2_volume(py::module& m);
void bind_cube2mat_corr_ret_absnextret(py::module& m);
void bind_cube2mat_corr_ret_n(py::module& m);
void bind_cube2mat_corr_ret_volume(py::module& m);
void bind_cube2mat_corr_signret_volume(py::module& m);
void bind_cube2mat_spearman_absret_volume(py::module& m);
void bind_cube2mat_absret_on_sqrtn_beta(py::module& m);
void bind_cube2mat_marubozu_density(py::module& m);
void bind_cube2mat_premkt_to_rth_ret_corr(py::module& m);
void bind_cube2mat_xcorr_n_absret_lag1(py::module& m);
void bind_cube2mat_xcorr_sign_volume_leadlag_lag(py::module& m);
void bind_cube2mat_xcorr_sign_volume_leadlag_peak(py::module& m);
void bind_cube2mat_xcorr_volume_absret_lag1(py::module& m);
void bind_cube2mat_absret_sqrtvol_slope(py::module& m);
void bind_cube2mat_impact_elasticity_log(py::module& m);
void bind_cube2mat_impact_reversion_beta1(py::module& m);
void bind_cube2mat_kyle_lambda_lead1_beta(py::module& m);
void bind_cube2mat_kyle_lambda_proxy(py::module& m);
void bind_cube2mat_log_absret_on_logvolume_beta(py::module& m);
void bind_cube2mat_absret_per_volume(py::module& m);
void bind_cube2mat_amihud_illiquidity(py::module& m);
void bind_cube2mat_avg_trade_size(py::module& m);
void bind_cube2mat_cv_n(py::module& m);
void bind_cube2mat_cv_trade_size(py::module& m);
void bind_cube2mat_cv_volume(py::module& m);
void bind_cube2mat_mean_volume_per_trade_down(py::module& m);
void bind_cube2mat_mean_volume_per_trade_up(py::module& m);
void bind_cube2mat_mvpt_up_over_down_ratio(py::module& m);
void bind_cube2mat_rv_per_trade(py::module& m);
void bind_cube2mat_rv_per_volume(py::module& m);
void bind_cube2mat_signed_volume_imbalance(py::module& m);
void bind_cube2mat_std_trade_size(py::module& m);
void bind_cube2mat_volume_share_on_down(py::module& m);
void bind_cube2mat_volume_share_on_up(py::module& m);
void bind_cube2mat_volume_top3_share(py::module& m);
void bind_cube2mat_volume_up_down_logratio(py::module& m);
void bind_cube2mat_vw_mean_absret_logret(py::module& m);
void bind_cube2mat_mutual_info_ret_volume_q8(py::module& m);
void bind_cube2mat_next_absret_after_top_vol_decile(py::module& m);
void bind_cube2mat_return_contribution_top_quintile_by_volume(py::module& m);
void bind_cube2mat_volume_compaction_80pct_bars_frac(py::module& m);
void bind_cube2mat_volume_front_loading_score(py::module& m);
void bind_cube2mat_volume_return_cokurtosis22(py::module& m);
void bind_cube2mat_volume_return_coskewness(py::module& m);
void bind_cube2mat_count_extreme_k_sigma(py::module& m);
void bind_cube2mat_jump_count_local_k3_win21(py::module& m);
void bind_cube2mat_jump_var_bns(py::module& m);
void bind_cube2mat_mean_over_median_absret(py::module& m);
void bind_cube2mat_rv_after_shock_share_k10(py::module& m);
void bind_cube2mat_shock_cluster_density_q90_win5(py::module& m);
void bind_cube2mat_shock_followthrough_score_k5(py::module& m);
void bind_cube2mat_shock_nextbar_reversion_ratio(py::module& m);
void bind_cube2mat_tail_imbalance_q95_logret(py::module& m);
void bind_cube2mat_ac1_absret(py::module& m);
void bind_cube2mat_ac1_ret2(py::module& m);
void bind_cube2mat_bpv_to_rv_ratio(py::module& m);
void bind_cube2mat_early_late_vol_ratio_30m(py::module& m);
void bind_cube2mat_early_late_vol_ratio_60m(py::module& m);
void bind_cube2mat_ewma_rvol_logret_094(py::module& m);
void bind_cube2mat_iqr_vol_logret(py::module& m);
void bind_cube2mat_return_vol_u_shape_ratio(py::module& m);
void bind_cube2mat_robust_vol_mad_ret(py::module& m);
void bind_cube2mat_rq_logret(py::module& m);
void bind_cube2mat_rv_compaction_50pct_bars_frac(py::module& m);
void bind_cube2mat_rv_compaction_80pct_bars_frac(py::module& m);
void bind_cube2mat_rv_cond_down(py::module& m);
void bind_cube2mat_rv_cond_up(py::module& m);
void bind_cube2mat_rv_last15m_share(py::module& m);
void bind_cube2mat_rv_truncated_logret_k35(py::module& m);
void bind_cube2mat_rv_winsorized_logret_k35(py::module& m);
void bind_cube2mat_rvol_ewma_logret_097(py::module& m);
void bind_cube2mat_rvol_logret(py::module& m);
void bind_cube2mat_rvol_over_sqrt_trades(py::module& m);
void bind_cube2mat_var_conc_top_decile(py::module& m);
void bind_cube2mat_vol_of_vol_absret(py::module& m);
void bind_cube2mat_cond_diff_next_ret_up_minus_down(py::module& m);
void bind_cube2mat_down_mean_absret(py::module& m);
void bind_cube2mat_endgame_drift_share_last60(py::module& m);
void bind_cube2mat_neg_semivar_ret(py::module& m);
void bind_cube2mat_next_ret_after_top_absret_decile(py::module& m);
void bind_cube2mat_next_ret_cond_down(py::module& m);
void bind_cube2mat_next_ret_cond_up(py::module& m);
void bind_cube2mat_oc_return_last30m_share(py::module& m);
void bind_cube2mat_opening_impulse_share_30m(py::module& m);
void bind_cube2mat_pac_ret_lag1_5(py::module& m);
void bind_cube2mat_pos_semivar_ret(py::module& m);
void bind_cube2mat_ret_up_down_abs_magnitude_ratio(py::module& m);
void bind_cube2mat_reversal_prob_after_big_down(py::module& m);
void bind_cube2mat_reversal_prob_after_big_up(py::module& m);
void bind_cube2mat_share_in_runs_len_ge3(py::module& m);
void bind_cube2mat_transition_asymmetry(py::module& m);
void bind_cube2mat_up_down_absret_ratio(py::module& m);
void bind_cube2mat_up_mean_absret(py::module& m);
void bind_cube2mat_vwap_cross_down_nextret(py::module& m);
void bind_cube2mat_vwap_cross_up_nextret(py::module& m);
void bind_cube2mat_zero_ret_share(py::module& m);
void bind_cube2mat_absret_compaction_80pct_bars_frac(py::module& m);
void bind_cube2mat_bpv_logret(py::module& m);
void bind_cube2mat_dc_count_bps_10(py::module& m);
void bind_cube2mat_lz_complexity_signret(py::module& m);
void bind_cube2mat_midday_smallmove_share_q25(py::module& m);
void bind_cube2mat_next3_absret_highvol_minus_lowvol(py::module& m);
void bind_cube2mat_qn_vol_logret(py::module& m);
void bind_cube2mat_roll_spread(py::module& m);
void bind_cube2mat_semivar_pos_over_neg(py::module& m);
void bind_cube2mat_signret_majority_agreement_share_m5(py::module& m);
void bind_cube2mat_turning_point_count(py::module& m);
void bind_cube2mat_vwap_cross_spacing_mean(py::module& m);
void bind_cube2mat_absret_center_of_mass_time(py::module& m);
void bind_cube2mat_absret_peak_time_frac(py::module& m);
void bind_cube2mat_absret_peak_time_min(py::module& m);
void bind_cube2mat_ac1_n(py::module& m);
void bind_cube2mat_ac1_volume(py::module& m);
void bind_cube2mat_ac_ret_lag2(py::module& m);
void bind_cube2mat_ac_ret_lag5(py::module& m);
void bind_cube2mat_accel_align_rate(py::module& m);
void bind_cube2mat_accel_over_vel_std_ratio(py::module& m);
void bind_cube2mat_ar1_ret_coef(py::module& m);
void bind_cube2mat_bars_to_50pct_volume_time_frac(py::module& m);
void bind_cube2mat_close_15m_absret_share(py::module& m);
void bind_cube2mat_close_15m_volume_share(py::module& m);
void bind_cube2mat_close_on_logn_beta(py::module& m);
void bind_cube2mat_close_on_logvolume_beta(py::module& m);
void bind_cube2mat_close_on_n_beta(py::module& m);
void bind_cube2mat_close_on_volume_beta(py::module& m);
void bind_cube2mat_close_on_vwap_beta(py::module& m);
void bind_cube2mat_close_to_open_ret(py::module& m);
void bind_cube2mat_clv_session(py::module& m);
void bind_cube2mat_corr_absret_volume(py::module& m);
void bind_cube2mat_corr_close_volume(py::module& m);
void bind_cube2mat_corr_close_vwap(py::module& m);
void bind_cube2mat_cv_close(py::module& m);
void bind_cube2mat_diff_close_vwap_on_volume_beta(py::module& m);
void bind_cube2mat_diff_close_vwap_trend_slope(py::module& m);
void bind_cube2mat_down_bar_share(py::module& m);
void bind_cube2mat_duration_since_last_vwap_cross_frac(py::module& m);
void bind_cube2mat_ema20_trend_align_share(py::module& m);
void bind_cube2mat_garman_klass_session_vol(py::module& m);
void bind_cube2mat_gk_var_sum_ohlc(py::module& m);
void bind_cube2mat_hurst_rs_ret(py::module& m);
void bind_cube2mat_impact_slope_price_cumn(py::module& m);
void bind_cube2mat_impact_slope_price_cumvol(py::module& m);
void bind_cube2mat_intraday_max_drawup_close(py::module& m);
void bind_cube2mat_jump_count_local_q95(py::module& m);
void bind_cube2mat_ljung_box_q_5(py::module& m);
void bind_cube2mat_max_absret_value(py::module& m);
void bind_cube2mat_mean_abs_vwap_gap(py::module& m);
void bind_cube2mat_mean_close_vwap_rel_diff(py::module& m);
void bind_cube2mat_midday_lull_rv_ratio(py::module& m);
void bind_cube2mat_midday_volume_ratio(py::module& m);
void bind_cube2mat_midrange_cross_count(py::module& m);
void bind_cube2mat_motif_ascending_share_m3_close(py::module& m);
void bind_cube2mat_motif_zigzag_share_m3_close(py::module& m);
void bind_cube2mat_n_burstiness(py::module& m);
void bind_cube2mat_n_fano_factor(py::module& m);
void bind_cube2mat_n_front_loading_score(py::module& m);
void bind_cube2mat_n_hhi(py::module& m);
void bind_cube2mat_n_peak_time_min(py::module& m);
void bind_cube2mat_near_close_ramp_slope_10m(py::module& m);
void bind_cube2mat_open_15m_absret_share(py::module& m);
void bind_cube2mat_open_15m_volume_share(py::module& m);
void bind_cube2mat_open_to_close_ret(py::module& m);
void bind_cube2mat_partial_corr_absret_volume_time(py::module& m);
void bind_cube2mat_partial_corr_close_n_time(py::module& m);
void bind_cube2mat_partial_corr_close_volume_time(py::module& m);
void bind_cube2mat_partial_corr_vwapdev_volume_time(py::module& m);
void bind_cube2mat_post_mean_close(py::module& m);
void bind_cube2mat_post_std_close(py::module& m);
void bind_cube2mat_post_std_ret(py::module& m);
void bind_cube2mat_pre_mean_close(py::module& m);
void bind_cube2mat_pre_std_close(py::module& m);
void bind_cube2mat_pre_std_ret(py::module& m);
void bind_cube2mat_premium_close_vwap_up_minus_down(py::module& m);
void bind_cube2mat_premkt_gap_fill_ratio(py::module& m);
void bind_cube2mat_price_above_median_share(py::module& m);
void bind_cube2mat_relprice_log_elasticity_n(py::module& m);
void bind_cube2mat_relprice_log_elasticity_volume(py::module& m);
void bind_cube2mat_ret_es_q05(py::module& m);
void bind_cube2mat_ret_excess_kurtosis(py::module& m);
void bind_cube2mat_ret_next_on_vwapdev_beta(py::module& m);
void bind_cube2mat_ret_var_q05(py::module& m);
void bind_cube2mat_rms_vwap_dev_rel(py::module& m);
void bind_cube2mat_rogers_satchell_session_vol(py::module& m);
void bind_cube2mat_run_count_total(py::module& m);
void bind_cube2mat_rv_close_vwap_diff(py::module& m);
void bind_cube2mat_rv_cond_above_vwap(py::module& m);
void bind_cube2mat_rv_cond_below_vwap(py::module& m);
void bind_cube2mat_rv_front_loading_score(py::module& m);
void bind_cube2mat_rv_last30m_share(py::module& m);
void bind_cube2mat_rv_logret(py::module& m);
void bind_cube2mat_rv_logret_15m(py::module& m);
void bind_cube2mat_rv_logret_30m(py::module& m);
void bind_cube2mat_rv_logret_5m(py::module& m);
void bind_cube2mat_rv_per_min_logret(py::module& m);
void bind_cube2mat_rv_share_above_vwap(py::module& m);
void bind_cube2mat_shock_calm_time_median_q50(py::module& m);
void bind_cube2mat_spearman_close_n(py::module& m);
void bind_cube2mat_spearman_close_volume(py::module& m);
void bind_cube2mat_spectral_entropy_close(py::module& m);
void bind_cube2mat_std_close(py::module& m);
void bind_cube2mat_std_close_vwap_diff(py::module& m);
void bind_cube2mat_std_n(py::module& m);
void bind_cube2mat_std_ret(py::module& m);
void bind_cube2mat_std_volume(py::module& m);
void bind_cube2mat_std_vwap_dev_rel(py::module& m);
void bind_cube2mat_theil_sen_slope_close_time(py::module& m);
void bind_cube2mat_time_share_above_open(py::module& m);
void bind_cube2mat_time_share_above_twap(py::module& m);
void bind_cube2mat_time_share_above_vwap(py::module& m);
void bind_cube2mat_time_to_20pct_volume_frac(py::module& m);
void bind_cube2mat_time_to_20pct_volume_min(py::module& m);
void bind_cube2mat_time_to_50pct_volume_frac(py::module& m);
void bind_cube2mat_time_to_50pct_volume_min(py::module& m);
void bind_cube2mat_time_to_first_extreme_q90_absret_frac(py::module& m);
void bind_cube2mat_time_to_half_openclose_ret_frac(py::module& m);

PYBIND11_MODULE(machine_alpha, m) {
    m.doc() = "collection of intraday features";
    bind_alpha_example(m);
    bind_cube2mat_gini_absret(m);
    bind_cube2mat_n_entropy_concentration(m);
    bind_cube2mat_n_gini(m);
    bind_cube2mat_ret_skew(m);
    bind_cube2mat_rv_entropy_concentration(m);
    bind_cube2mat_rv_gini_concentration(m);
    bind_cube2mat_trade_size_gini(m);
    bind_cube2mat_trend_resid_kurt(m);
    bind_cube2mat_trend_resid_skew(m);
    bind_cube2mat_volume_entropy_concentration(m);
    bind_cube2mat_volume_gini(m);
    bind_cube2mat_volume_median_to_mean_ratio(m);
    bind_cube2mat_volume_skew(m);
    bind_cube2mat_katz_fd_close(m);
    bind_cube2mat_oc_efficiency_over_range(m);
    bind_cube2mat_path_efficiency(m);
    bind_cube2mat_path_length_over_range(m);
    bind_cube2mat_total_variation_close(m);
    bind_cube2mat_breakout_nextret_high(m);
    bind_cube2mat_breakout_nextret_low(m);
    bind_cube2mat_candle_body_to_range_mean(m);
    bind_cube2mat_close_to_edge_distance_frac(m);
    bind_cube2mat_doji_density(m);
    bind_cube2mat_end_position_in_range(m);
    bind_cube2mat_intraday_max_drawdown_close(m);
    bind_cube2mat_iqr_logret(m);
    bind_cube2mat_lower_shadow_ratio_mean(m);
    bind_cube2mat_max_drawdown_depth_per_bar(m);
    bind_cube2mat_mean_body_to_range(m);
    bind_cube2mat_median_position_in_range(m);
    bind_cube2mat_n_peak_time_frac(m);
    bind_cube2mat_near_high_time_share_10bp(m);
    bind_cube2mat_near_low_time_share_10bp(m);
    bind_cube2mat_new_high_count(m);
    bind_cube2mat_new_low_count(m);
    bind_cube2mat_parkinson_vol(m);
    bind_cube2mat_range_on_logvolume_beta(m);
    bind_cube2mat_range_per_trade(m);
    bind_cube2mat_range_to_rv_sqrt_ratio(m);
    bind_cube2mat_range_up_down_ratio(m);
    bind_cube2mat_spectral_lowfreq_share_close(m);
    bind_cube2mat_time_share_mid_range_20pct(m);
    bind_cube2mat_u_shape_corr_volume(m);
    bind_cube2mat_upper_shadow_ratio_mean(m);
    bind_cube2mat_vwap_position_in_range(m);
    bind_cube2mat_wavelet_energy_highfreq_share(m);
    bind_cube2mat_wavelet_energy_lowfreq_share(m);
    bind_cube2mat_cond_reversal_after_run2(m);
    bind_cube2mat_early_vs_late_run_count_ratio(m);
    bind_cube2mat_max_down_run_len(m);
    bind_cube2mat_max_up_run_len(m);
    bind_cube2mat_mean_run_length_sign(m);
    bind_cube2mat_quietest_stretch_maxlen_q25_absret_frac(m);
    bind_cube2mat_run_balance_index(m);
    bind_cube2mat_run_len_var_ratio_up_to_down(m);
    bind_cube2mat_run_length_entropy_signret(m);
    bind_cube2mat_sign_change_rate(m);
    bind_cube2mat_swing_amplitude_median(m);
    bind_cube2mat_transition_p_same_sign(m);
    bind_cube2mat_approx_entropy_absret_m2_r02(m);
    bind_cube2mat_entropy_sign_ret(m);
    bind_cube2mat_higuchi_fd_logret_kmax7(m);
    bind_cube2mat_permutation_entropy_logret_m3(m);
    bind_cube2mat_permutation_entropy_ret(m);
    bind_cube2mat_sample_entropy_absret_m2_r02(m);
    bind_cube2mat_transition_entropy_signret(m);
    bind_cube2mat_volume_entropy(m);
    bind_cube2mat_corr_absret_n(m);
    bind_cube2mat_corr_ret2_volume(m);
    bind_cube2mat_corr_ret_absnextret(m);
    bind_cube2mat_corr_ret_n(m);
    bind_cube2mat_corr_ret_volume(m);
    bind_cube2mat_corr_signret_volume(m);
    bind_cube2mat_spearman_absret_volume(m);
    bind_cube2mat_absret_on_sqrtn_beta(m);
    bind_cube2mat_marubozu_density(m);
    bind_cube2mat_premkt_to_rth_ret_corr(m);
    bind_cube2mat_xcorr_n_absret_lag1(m);
    bind_cube2mat_xcorr_sign_volume_leadlag_lag(m);
    bind_cube2mat_xcorr_sign_volume_leadlag_peak(m);
    bind_cube2mat_xcorr_volume_absret_lag1(m);
    bind_cube2mat_absret_sqrtvol_slope(m);
    bind_cube2mat_impact_elasticity_log(m);
    bind_cube2mat_impact_reversion_beta1(m);
    bind_cube2mat_kyle_lambda_lead1_beta(m);
    bind_cube2mat_kyle_lambda_proxy(m);
    bind_cube2mat_log_absret_on_logvolume_beta(m);
    bind_cube2mat_absret_per_volume(m);
    bind_cube2mat_amihud_illiquidity(m);
    bind_cube2mat_avg_trade_size(m);
    bind_cube2mat_cv_n(m);
    bind_cube2mat_cv_trade_size(m);
    bind_cube2mat_cv_volume(m);
    bind_cube2mat_mean_volume_per_trade_down(m);
    bind_cube2mat_mean_volume_per_trade_up(m);
    bind_cube2mat_mvpt_up_over_down_ratio(m);
    bind_cube2mat_rv_per_trade(m);
    bind_cube2mat_rv_per_volume(m);
    bind_cube2mat_signed_volume_imbalance(m);
    bind_cube2mat_std_trade_size(m);
    bind_cube2mat_volume_share_on_down(m);
    bind_cube2mat_volume_share_on_up(m);
    bind_cube2mat_volume_top3_share(m);
    bind_cube2mat_volume_up_down_logratio(m);
    bind_cube2mat_vw_mean_absret_logret(m);
    bind_cube2mat_mutual_info_ret_volume_q8(m);
    bind_cube2mat_next_absret_after_top_vol_decile(m);
    bind_cube2mat_return_contribution_top_quintile_by_volume(m);
    bind_cube2mat_volume_compaction_80pct_bars_frac(m);
    bind_cube2mat_volume_front_loading_score(m);
    bind_cube2mat_volume_return_cokurtosis22(m);
    bind_cube2mat_volume_return_coskewness(m);
    bind_cube2mat_count_extreme_k_sigma(m);
    bind_cube2mat_jump_count_local_k3_win21(m);
    bind_cube2mat_jump_var_bns(m);
    bind_cube2mat_mean_over_median_absret(m);
    bind_cube2mat_rv_after_shock_share_k10(m);
    bind_cube2mat_shock_cluster_density_q90_win5(m);
    bind_cube2mat_shock_followthrough_score_k5(m);
    bind_cube2mat_shock_nextbar_reversion_ratio(m);
    bind_cube2mat_tail_imbalance_q95_logret(m);
    bind_cube2mat_ac1_absret(m);
    bind_cube2mat_ac1_ret2(m);
    bind_cube2mat_bpv_to_rv_ratio(m);
    bind_cube2mat_early_late_vol_ratio_30m(m);
    bind_cube2mat_early_late_vol_ratio_60m(m);
    bind_cube2mat_ewma_rvol_logret_094(m);
    bind_cube2mat_iqr_vol_logret(m);
    bind_cube2mat_return_vol_u_shape_ratio(m);
    bind_cube2mat_robust_vol_mad_ret(m);
    bind_cube2mat_rq_logret(m);
    bind_cube2mat_rv_compaction_50pct_bars_frac(m);
    bind_cube2mat_rv_compaction_80pct_bars_frac(m);
    bind_cube2mat_rv_cond_down(m);
    bind_cube2mat_rv_cond_up(m);
    bind_cube2mat_rv_last15m_share(m);
    bind_cube2mat_rv_truncated_logret_k35(m);
    bind_cube2mat_rv_winsorized_logret_k35(m);
    bind_cube2mat_rvol_ewma_logret_097(m);
    bind_cube2mat_rvol_logret(m);
    bind_cube2mat_rvol_over_sqrt_trades(m);
    bind_cube2mat_var_conc_top_decile(m);
    bind_cube2mat_vol_of_vol_absret(m);
    bind_cube2mat_cond_diff_next_ret_up_minus_down(m);
    bind_cube2mat_down_mean_absret(m);
    bind_cube2mat_endgame_drift_share_last60(m);
    bind_cube2mat_neg_semivar_ret(m);
    bind_cube2mat_next_ret_after_top_absret_decile(m);
    bind_cube2mat_next_ret_cond_down(m);
    bind_cube2mat_next_ret_cond_up(m);
    bind_cube2mat_oc_return_last30m_share(m);
    bind_cube2mat_opening_impulse_share_30m(m);
    bind_cube2mat_pac_ret_lag1_5(m);
    bind_cube2mat_pos_semivar_ret(m);
    bind_cube2mat_ret_up_down_abs_magnitude_ratio(m);
    bind_cube2mat_reversal_prob_after_big_down(m);
    bind_cube2mat_reversal_prob_after_big_up(m);
    bind_cube2mat_share_in_runs_len_ge3(m);
    bind_cube2mat_transition_asymmetry(m);
    bind_cube2mat_up_down_absret_ratio(m);
    bind_cube2mat_up_mean_absret(m);
    bind_cube2mat_vwap_cross_down_nextret(m);
    bind_cube2mat_vwap_cross_up_nextret(m);
    bind_cube2mat_zero_ret_share(m);
    bind_cube2mat_absret_compaction_80pct_bars_frac(m);
    bind_cube2mat_bpv_logret(m);
    bind_cube2mat_dc_count_bps_10(m);
    bind_cube2mat_lz_complexity_signret(m);
    bind_cube2mat_midday_smallmove_share_q25(m);
    bind_cube2mat_next3_absret_highvol_minus_lowvol(m);
    bind_cube2mat_qn_vol_logret(m);
    bind_cube2mat_roll_spread(m);
    bind_cube2mat_semivar_pos_over_neg(m);
    bind_cube2mat_signret_majority_agreement_share_m5(m);
    bind_cube2mat_turning_point_count(m);
    bind_cube2mat_vwap_cross_spacing_mean(m);
    bind_cube2mat_absret_center_of_mass_time(m);
    bind_cube2mat_absret_peak_time_frac(m);
    bind_cube2mat_absret_peak_time_min(m);
    bind_cube2mat_ac1_n(m);
    bind_cube2mat_ac1_volume(m);
    bind_cube2mat_ac_ret_lag2(m);
    bind_cube2mat_ac_ret_lag5(m);
    bind_cube2mat_accel_align_rate(m);
    bind_cube2mat_accel_over_vel_std_ratio(m);
    bind_cube2mat_ar1_ret_coef(m);
    bind_cube2mat_bars_to_50pct_volume_time_frac(m);
    bind_cube2mat_close_15m_absret_share(m);
    bind_cube2mat_close_15m_volume_share(m);
    bind_cube2mat_close_on_logn_beta(m);
    bind_cube2mat_close_on_logvolume_beta(m);
    bind_cube2mat_close_on_n_beta(m);
    bind_cube2mat_close_on_volume_beta(m);
    bind_cube2mat_close_on_vwap_beta(m);
    bind_cube2mat_close_to_open_ret(m);
    bind_cube2mat_clv_session(m);
    bind_cube2mat_corr_absret_volume(m);
    bind_cube2mat_corr_close_volume(m);
    bind_cube2mat_corr_close_vwap(m);
    bind_cube2mat_cv_close(m);
    bind_cube2mat_diff_close_vwap_on_volume_beta(m);
    bind_cube2mat_diff_close_vwap_trend_slope(m);
    bind_cube2mat_down_bar_share(m);
    bind_cube2mat_duration_since_last_vwap_cross_frac(m);
    bind_cube2mat_ema20_trend_align_share(m);
    bind_cube2mat_garman_klass_session_vol(m);
    bind_cube2mat_gk_var_sum_ohlc(m);
    bind_cube2mat_hurst_rs_ret(m);
    bind_cube2mat_impact_slope_price_cumn(m);
    bind_cube2mat_impact_slope_price_cumvol(m);
    bind_cube2mat_intraday_max_drawup_close(m);
    bind_cube2mat_jump_count_local_q95(m);
    bind_cube2mat_ljung_box_q_5(m);
    bind_cube2mat_max_absret_value(m);
    bind_cube2mat_mean_abs_vwap_gap(m);
    bind_cube2mat_mean_close_vwap_rel_diff(m);
    bind_cube2mat_midday_lull_rv_ratio(m);
    bind_cube2mat_midday_volume_ratio(m);
    bind_cube2mat_midrange_cross_count(m);
    bind_cube2mat_motif_ascending_share_m3_close(m);
    bind_cube2mat_motif_zigzag_share_m3_close(m);
    bind_cube2mat_n_burstiness(m);
    bind_cube2mat_n_fano_factor(m);
    bind_cube2mat_n_front_loading_score(m);
    bind_cube2mat_n_hhi(m);
    bind_cube2mat_n_peak_time_min(m);
    bind_cube2mat_near_close_ramp_slope_10m(m);
    bind_cube2mat_open_15m_absret_share(m);
    bind_cube2mat_open_15m_volume_share(m);
    bind_cube2mat_open_to_close_ret(m);
    bind_cube2mat_partial_corr_absret_volume_time(m);
    bind_cube2mat_partial_corr_close_n_time(m);
    bind_cube2mat_partial_corr_close_volume_time(m);
    bind_cube2mat_partial_corr_vwapdev_volume_time(m);
    bind_cube2mat_post_mean_close(m);
    bind_cube2mat_post_std_close(m);
    bind_cube2mat_post_std_ret(m);
    bind_cube2mat_pre_mean_close(m);
    bind_cube2mat_pre_std_close(m);
    bind_cube2mat_pre_std_ret(m);
    bind_cube2mat_premium_close_vwap_up_minus_down(m);
    bind_cube2mat_premkt_gap_fill_ratio(m);
    bind_cube2mat_price_above_median_share(m);
    bind_cube2mat_relprice_log_elasticity_n(m);
    bind_cube2mat_relprice_log_elasticity_volume(m);
    bind_cube2mat_ret_es_q05(m);
    bind_cube2mat_ret_excess_kurtosis(m);
    bind_cube2mat_ret_next_on_vwapdev_beta(m);
    bind_cube2mat_ret_var_q05(m);
    bind_cube2mat_rms_vwap_dev_rel(m);
    bind_cube2mat_rogers_satchell_session_vol(m);
    bind_cube2mat_run_count_total(m);
    bind_cube2mat_rv_close_vwap_diff(m);
    bind_cube2mat_rv_cond_above_vwap(m);
    bind_cube2mat_rv_cond_below_vwap(m);
    bind_cube2mat_rv_front_loading_score(m);
    bind_cube2mat_rv_last30m_share(m);
    bind_cube2mat_rv_logret(m);
    bind_cube2mat_rv_logret_15m(m);
    bind_cube2mat_rv_logret_30m(m);
    bind_cube2mat_rv_logret_5m(m);
    bind_cube2mat_rv_per_min_logret(m);
    bind_cube2mat_rv_share_above_vwap(m);
    bind_cube2mat_shock_calm_time_median_q50(m);
    bind_cube2mat_spearman_close_n(m);
    bind_cube2mat_spearman_close_volume(m);
    bind_cube2mat_spectral_entropy_close(m);
    bind_cube2mat_std_close(m);
    bind_cube2mat_std_close_vwap_diff(m);
    bind_cube2mat_std_n(m);
    bind_cube2mat_std_ret(m);
    bind_cube2mat_std_volume(m);
    bind_cube2mat_std_vwap_dev_rel(m);
    bind_cube2mat_theil_sen_slope_close_time(m);
    bind_cube2mat_time_share_above_open(m);
    bind_cube2mat_time_share_above_twap(m);
    bind_cube2mat_time_share_above_vwap(m);
    bind_cube2mat_time_to_20pct_volume_frac(m);
    bind_cube2mat_time_to_20pct_volume_min(m);
    bind_cube2mat_time_to_50pct_volume_frac(m);
    bind_cube2mat_time_to_50pct_volume_min(m);
    bind_cube2mat_time_to_first_extreme_q90_absret_frac(m);
    bind_cube2mat_time_to_half_openclose_ret_frac(m);
}

